name: burn_severity_app
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  image: ^3.3.0  # keep your current major; newer 4.x is fine too
  lottie: ^2.7.0 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/water.json
    - assets/lottie/bandage.json
    - assets/lottie/warn.json

 
